name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.checkout.outputs.repo-path }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  lint-and-security:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Audit npm dependencies for vulnerabilities
        run: npm audit --production

  coverage:
    runs-on: ubuntu-latest
    needs: lint-and-security
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm run test -- --coverage

      - name: Generate Coverage Badge
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: coverage/lcov.info

      - name: Verify Changed Files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: README.md

      - name: Commit Coverage Badge to README
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badge."

      - name: Push Coverage Badge Update
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  sonarcloud-analysis:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Upload Coverage Report to SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: sonarcloud-analysis
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Build application with Vite
        run: npm run build

      - name: Upload artifact for GitHub Pages deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: build
          path: dist
