name: Continuous Integration

# This workflow is triggered on push, pull request events, and manual dispatch.
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

# Setting permissions for the workflow
permissions:
  contents: read  # Allows read access to the repository's contents
  id-token: write  # Allows write access for ID tokens

jobs:
  # Job for linting the code and checking security vulnerabilities
  lint-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  # Cache key based on OS and package-lock
          restore-keys: |
            ${{ runner.os }}-node-  # Restore keys for cache misses

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint  # Execute the linter to check code style

      - name: Audit npm dependencies for vulnerabilities
        run: npm audit --production  # Check for security vulnerabilities in dependencies

  # Job for running tests and generating coverage reports
  coverage:
    runs-on: ubuntu-latest
    needs: lint-and-security
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tests

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm run test -- --coverage  # Execute tests and generate coverage reports

      - name: Generate Coverage Badge
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: coverage/lcov.info  # Specify the coverage report file

      - name: Verify Changed Files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: README.md  # Check if README.md has changed

      - name: Commit Coverage Badge to README
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badge."  # Commit the updated badge if README changed

      - name: Push Coverage Badge Update
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}  # Push changes to the current branch

  # Job for uploading coverage reports to SonarCloud
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for analysis

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Upload Coverage Report to SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info  # Specify coverage report path
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarCloud token for authentication

  # Job for building the application
  build:
    runs-on: ubuntu-latest
    needs: sonarcloud-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for building

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Build application with Vite
        run: npm run build

      - name: Upload artifact for GitHub Pages deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: build
          path: dist  # Specify the path to the build artifacts
