# Workflow for building and deploying a Vue.js/Vite application to GitHub Pages
name: Deploy Vite with GitHub Pages

on:
  # Trigger the workflow when there's a push to the main branch
  push:
    branches: ["main"]

  # Allows the workflow to be manually triggered from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job to lint the code for best practices
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  # Job to audit the npm dependencies for security vulnerabilities
  security:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Audit npm dependencies for vulnerabilities
        run: npm audit --production

  # Job to build the Vite application
  build:
    runs-on: ubuntu-latest
    needs: [lint, security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Build application with Vite
        run: npm run build

      - name: Upload artifact for GitHub Pages deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist  # Directory where Vite outputs the production build

  # Job to deploy the built app to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
